version: '3'
services:
  php:
    build: 
      context: ./images/php
      dockerfile: Dockerfile
    volumes:
      - './Blood-Bank-Management-System:/var/www/html'
    environment:
      - USERNAME=root
      - PASSWORD=root
      - DB_NAME=bloodbank

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './docker/nginx/index.html:/usr/share/nginx/html/index.html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
      - './Blood-Bank-Management-System:/var/www/html'

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    ports:
      - 3306:3306
    volumes:
    - ./docker/mysql:/docker-entrypoint-initdb.d
    - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
